### ISSUE TITLE
Remove interface or abstract class logic

### ISSUE THREAD

**Issue by ruckc** [francisdb/serviceloader-maven-plugin#11]
It would be nice of you could remove the if(isInterface or isAbstract) logic, or at least create a configuration variable to disable the checking.  We utilize a modified ServiceLoader for loading extensions of non-abstract classes (the JAX-RS Application.class).

**Comment by francisdb** [comment]
Hi @ruckc 

The docs mention this: `For the purpose of loading, a service is represented by a single type, that is, a single interface or abstract class. (A concrete class can be used, but this is not recommended.)`
https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html

So there is indeed no reason to have that check in place. I'll get rid of it and roll a release.

**Comment by francisdb** [comment]
Version `1.0.5` that contains this fix should be available in maven central soon

**Comment by ruckc** [comment]
Thank you
