### ISSUE TITLE
Caveat on use with m2e (Maven in Eclipse)

### ISSUE THREAD

**Issue by tm2git** [francisdb/serviceloader-maven-plugin#9]
This isn't quite a bug report, more of a warning or an applicability statement.

This plugin is great, and I like the fact that it discovers the classes that implement the service interface (c.f. other approaches where you have to add an annotation to each service implementation class).  I  believe that it works fine in a pure Maven environment.

Where I got into trouble with it (and why I'll probably end up using one of those other approaches instead) was trying to use it with m2e in Eclipse.  This combination led to flakey behaviour:  often it worked fine, but occasionally I discovered at runtime that Eclipse/m2e had built a new version of the JAR file that hadn't executed the plugin and hence didn't contain the META-INF/services entry.  Bah.

I think I understand what caused this.  m2e places  extra requirements on Maven plugins:

        http://wiki.eclipse.org/M2E_compatible_maven_plugins#BuildContext

Since this plugin doesn't implement those m2e requirements, I ended up configuring m2e's lifecycleMappingMetadata with its action set to &lt;ignore/&gt; (rather than &lt;execute/&gt;), reasoning that it didn't really matter whether Eclipse builds worked, all that really mattered was the Maven builds (which work fine).  But this is exactly what led to the flakiness:  if the JAR file that I ended up with at runtime (in a web app built by Eclipse/m2e and deployed on Tomcat under Eclipse) had been produced by a Maven build then all was good, but if for whatever reason Eclipse/m2e had more recently executed an Eclipse build then I silently ended up with a JAR file that contained everything except the META-INF/services entry.

[Perhaps I could also use m2e's Maven --> Disable Workspace Resolution command to work around this (because then, I assume, the JAR artifact would always be a valid one from my local m2 repo rather than the close-but-no-cigar JAR file generated by Eclipse/m2e).  I haven't tried that approach].

I'm certainly not suggesting that this plugin should be modified to make it play by m2e's rules (that would be quite a bit of work).  Feel free to close this issue;  I mainly logged it as an FYI for anyone else who might try the combo of this (pretty neat) plugin and m2e.

**Comment by francisdb** [comment]
@berryma4 :+1:  will check the pull request andere build a new release early next week.

**Comment by francisdb** [comment]
I have no eclipse installed but trust this is working ;-)

**Comment by francisdb** [comment]
This has been released as version 1.0.4 and should appear in central shortly

**Comment by berryma4** [comment]
thank you again!

**Comment by francisdb** [comment]
All credits go to yourself :+1:
